### ISSUE TITLE
wher is directory?

### ISSUE THREAD

**Issue by majidmp97** [G6EJD/ESP32-8266-File-Download#1]
i program source but i don't have directory menu

![sd](https://user-images.githubusercontent.com/35567123/45026172-c5f86f80-b052-11e8-9e63-ddf1953e44a8.JPG)

**Comment by G6EJD** [comment]
What happens when you press 'download' ? It should launch a browser window that prompts for the file name to be entered and downloaded from the ESP8266
![sample](https://user-images.githubusercontent.com/6075568/45026649-74d68480-b02e-11e8-966b-a036d8249b90.jpg)

It's not a PC operating system, that can produce a file directory for you to choose and then download a file. You could prefix the download with a directory function that I have provided, then go straight to the download function for the entry so it all occurs on one html page...

Is this what you mean?

**Comment by majidmp97** [comment]
oh i download example just for download
this is full your example
thank you

https://github.com/G6EJD/ESP32-ESP8266-File-Download-Upload-Delete-Stream-and-Directory

**Comment by G6EJD** [comment]
On the esp8266 or 32 there will always be a compromise but it all works. Be aware the the http protocol means the overhead is quite high so larger transfers can take time, trial with a small file to begin with and expect many minutes with say 100K files, this is a facet of http.
